# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-01 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171101_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bit',
            new_name='bio',
        ),
    ]
