# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 13:19
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20171219_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
    ]
